# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of colopresso
#
# Copyright (C) 2025 COLOPL, Inc.
#
# Author: Go Kudo <g-kudo@colopl.co.jp>
# Developed with AI (LLM) code assistance. See `NOTICE` for details.

message(STATUS "Debug mode enabled")

option(COLOPRESSO_USE_VALGRIND "Use Valgrind if available" OFF)
option(COLOPRESSO_VALGRIND_RAYON_NUM_THREADS "RAYON_NUM_THREADS for Valgrind tests to avoid oversubscription" "1")
option(COLOPRESSO_VALGRIND_TRACK_ORIGINS "Enable Valgrind --track-origins (very slow)" OFF)
set(COLOPRESSO_VALGRIND_LEAK_CHECK "full" CACHE STRING "Valgrind --leak-check (no|summary|full)")
set(COLOPRESSO_VALGRIND_SHOW_LEAK_KINDS "all" CACHE STRING "Valgrind --show-leak-kinds")
option(COLOPRESSO_USE_COVERAGE "Use coverage if available" OFF)
option(COLOPRESSO_USE_ASAN "Use AddressSanitizer" OFF)
option(COLOPRESSO_USE_MSAN "Use MemorySanitizer" OFF)
option(COLOPRESSO_USE_UBSAN "Use UndefinedBehaviorSanitizer" OFF)

if(COLOPRESSO_USE_COVERAGE)
  if(COLOPRESSO_USE_VALGRIND)
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -g -Og -fno-omit-frame-pointer")
    message(STATUS "Valgrind enabled: using -Og for faster Debug builds")
  else()
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -g -O0 -fno-inline -fno-omit-frame-pointer")
  endif()
endif()

if(COLOPRESSO_USE_COVERAGE)
  if(NOT CMAKE_C_COMPILER_ID MATCHES "GNU")
    message(FATAL_ERROR "Coverage is only supported with GNU C compilers")
  endif()

  find_program(LCOV lcov)
  find_program(GENHTML genhtml)

  if(LCOV AND GENHTML)
    set(COLOPRESSO_ENABLE_COVERAGE ON)
    link_libraries(gcov)
    message(STATUS "Coverage enabled with lcov/gcov")
  else()
    message(FATAL_ERROR "lcov or genhtml not found")
  endif()
else()
  set(COLOPRESSO_ENABLE_COVERAGE OFF)
endif()

set(_colopresso_sanitizers)
if(COLOPRESSO_USE_ASAN)
  list(APPEND _colopresso_sanitizers address)
endif()
if(COLOPRESSO_USE_MSAN)
  list(APPEND _colopresso_sanitizers memory)
endif()
if(COLOPRESSO_USE_UBSAN)
  list(APPEND _colopresso_sanitizers undefined)
endif()

if(_colopresso_sanitizers)
  if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "Sanitizers are only supported with clang compilers")
  endif()

  if(COLOPRESSO_USE_ASAN AND COLOPRESSO_USE_MSAN)
    message(FATAL_ERROR "ASAN and MSAN cannot be used together")
  endif()

  if(COLOPRESSO_USE_MSAN)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
      set(PNG_ARM_NEON off CACHE STRING "Disable Arm NEON with MemorySanitizer" FORCE)
      message(STATUS "Disabling libpng Arm NEON optimizations for MemorySanitizer compatibility")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
      set(ENABLE_NASM 0 CACHE BOOL "Disable NASM/assembly for libaom under MemorySanitizer" FORCE)
      message(STATUS "Disabling libaom NASM/assembly optimizations for MemorySanitizer compatibility")
    endif()

    set(AOM_TARGET_CPU "generic" CACHE STRING "Use generic libaom build under MemorySanitizer" FORCE)
    message(STATUS "Setting libaom target CPU to 'generic' for MemorySanitizer compatibility")
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
      message(STATUS "Keeping libwebp SIMD enabled under MemorySanitizer on amd64 (disabling SSE2 is ABI-incompatible)")
    else()
      set(WEBP_ENABLE_SIMD OFF CACHE BOOL "Disable libwebp SIMD for MemorySanitizer" FORCE)
      message(STATUS "Disabling libwebp SIMD optimizations for MemorySanitizer compatibility")
    endif()
  endif()

  set(_colopresso_sanitizer_flags)
  foreach(_sanitizer ${_colopresso_sanitizers})
    list(APPEND _colopresso_sanitizer_flags "-fsanitize=${_sanitizer}")
    if(_sanitizer STREQUAL "address")
      message(STATUS "AddressSanitizer enabled")
    elseif(_sanitizer STREQUAL "memory")
      message(STATUS "MemorySanitizer enabled")
    elseif(_sanitizer STREQUAL "undefined")
      message(STATUS "UndefinedBehaviorSanitizer enabled")
    endif()
  endforeach()

  string(JOIN " " _colopresso_sanitizer_string ${_colopresso_sanitizer_flags})
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${_colopresso_sanitizer_string}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${_colopresso_sanitizer_string}")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_colopresso_sanitizer_string}")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${_colopresso_sanitizer_string}")
else()
  find_program(VALGRIND "valgrind")
  if(COLOPRESSO_USE_VALGRIND AND VALGRIND)
    message(STATUS "Found Valgrind: ${VALGRIND}")
    set(COLOPRESSO_ENABLE_VALGRIND ON)
  else()
    set(COLOPRESSO_ENABLE_VALGRIND OFF)
  endif()
endif()
